### PR TITLE
Add Ability to pull in rules from remote repos #1

### PR DESCRIPTION
**Pull request by mkcomer**
To test this PR: 

go build 
go run main.go -c "https://raw.githubusercontent.com/get-woke/woke/main/example.yaml" --debug

### CODE REVIEW

**Comment by caitlinelfring** [comment]
Before I review, there is a merge conflict and it appears this PR is trying to revert a bunch of the recent commits to the main branch. Thanks!

**Comment by caitlinelfring** [comment]
Also, please update the PR description based on the PR template so you can provide more details on your PR: https://github.com/get-woke/woke/blob/main/.github/PULL_REQUEST_TEMPLATE.md

**Comment by mkcomer** [comment]
I will be merging this into our forked repo first! Accidentally submitted this. I will update and resubmit a MR here.

**Comment by caitlinelfring** [comment]
No worries, excited for this feature! Thanks!

**Pull request closed without merging**
